### ISSUE TITLE
search screen

### ISSUE THREAD

**Issue by SirGeoffreyB** [yodigi7/credo-database#13]
To find users
a. for events
b. to edit the info
c. to look up info

[https://docs.google.com/drawings/d/1CUw1hesf5w6ZoN570zSC8lhJUNjx9CkvAkBdcm28U94/edit](https://docs.google.com/drawings/d/1CUw1hesf5w6ZoN570zSC8lhJUNjx9CkvAkBdcm28U94/edit)

**Comment by SirGeoffreyB** [comment]
Would having a search button on the original screen be a reasonable alternative?

Maybe have it mark searchable fields with a red border or lettering or in some other way?

Then when a Search Button is clicked with some text that is being searched for input a screen with the searched for field(s) shows and below that a list of the records that meet the search criteria shows below that with a clickable link on each one, or an option (eg. a button or link) to download the results as a .csv file.

Another alternative to having the list below the search field could be a pop out window with a spreadsheet style list of results.

**Comment by yodigi7** [comment]
@SirGeoffreyB show with visuals not just an empty box and text, very sparse diagram that doesn't show anything about the results list, show me with visuals and not descriptive text.

**Comment by yodigi7** [comment]
@SirGeoffreyB pushed to heroku
