### ISSUE TITLE
Standardization of state inputs

### ISSUE THREAD

**Issue by SirGeoffreyB** [yodigi7/credo-database#22]
A dropdown list for states with the two letter abbreviation followed by the state name spelled out?

Or perhaps a template that requires or fixes lower case abbreviations.

Currently Missouri could be MO, mo, mO, Missourah, Missouri, Mizzery or whatever misspellings that might occur.

**Comment by yodigi7** [comment]
What do you prefer the formatting be? Do we limit them to only a large dropdown or what?
