### ISSUE TITLE
transaction page connections

### ISSUE THREAD

**Issue by SirGeoffreyB** [yodigi7/credo-database#27]
Set up transactions page.

https://docs.google.com/drawings/d/1qKlLPDsmLgVIF___f-a8l9cHFxAQ_7sOz9B7Wptkqoo/edit

Ideally we could import up to 12 name tags (or more) for someone purchasing at table of 12 online. Most people will be purchasing fewer than that, of course. We have had people purchase a couple of tables, however.

**Comment by yodigi7** [comment]
Got a first start on this. Try [here](https://credo-jhipster-database.herokuapp.com/person/10001/add-transaction)
Going to need to talk to you about the specifics, not very clear of the objective of the form/subforms and why information is in the form such as address. Why?

**Comment by SirGeoffreyB** [comment]
transaction input page version 2
https://docs.google.com/drawings/d/1PqYTg5Q2pzZ12q8x7SaXEx3CD5DdZBqkfJkIMeKNPOU/edit

**Comment by SirGeoffreyB** [comment]
On that transactions page:
The gray background input boxes are prefilled from the CREATE/EDIT PERSON screen.
The green total amount for this transaction box is calculated by adding the columns to the right of the vertical line.
The white boxes are for input.
Total ticket purchases box is auto calculated from input in the cost/ticket box and the # of tickets box.

**Comment by SirGeoffreyB** [comment]
If someone bought 2 or more memberships, the spouse search would pull up the HH which would show the purchase of the multiple memberships in the transactions section.

**Comment by yodigi7** [comment]
For the v2, where did the name tags go or will you not input those since this form will be only for "at the door" ticket sales that don't matter if they have it in the db or not?
