### ISSUE TITLE
Search page for day of event

### ISSUE THREAD

**Issue by SirGeoffreyB** [yodigi7/credo-database#28]
So volunteers can tell how many tickets, if any, a person coming to their table has purchased.

This is a critically important feature that will be needed long enough before the July 10th event that we can train volunteers well enough to be comfortable using it in a crowd of impatient people

**Comment by yodigi7** [comment]
Do a google draw for how it is supposed to look.

**Comment by SirGeoffreyB** [comment]
Ticket lookup form for the day of an event:

https://docs.google.com/drawings/d/1heQKR9zJF5Z16ejB0HtJp0IONWr-Ejh428zxl3-jrps/edit?usp=sharing

**Comment by yodigi7** [comment]
Going to use the normal lookup form for person and just use this as the view page. Also, @SirGeoffreyB post the latest link here.

**Comment by SirGeoffreyB** [comment]
Goal posts moved....
