### ISSUE TITLE
Compress input screen a bit

### ISSUE THREAD

**Issue by SirGeoffreyB** [yodigi7/credo-database#30]
Description of "Member Since" and "Member Expiration" input fields are on two lines, one for the description & 1 showing the input format for a calendar date. Those could be compressed by putting the description in the input box and a little calendar icon in the box as well. See "[Image 1](https://imgur.com/oB6zSJl)" for the current input, and "[Image 2](https://imgur.com/IhpxQ3V)" for a more compressed look and to reduce the need for scrolling.

The deceased?  box could be moved up a line as well.

**Comment by SirGeoffreyB** [comment]
More compression of the input screen.

[current](https://credo-jhipster-database.herokuapp.com/edit-person/10001)

[proposed](https://docs.google.com/drawings/d/1PkjICXdRzGRbzC9SPi5hZvs3HiRXBx_iHChGZ3NIFOo/edit?usp=sharing)

Move the Add Address, Add Spouse and Add Household member all onto one horizontal line, rather than two.

Have the default box for Notes and Mailing Label shrunk down to one horizontal line, which can be expanded if more lines are needed.

Put the "Receive Mail" description inside of the input box rather than above it.

Move the Add Transaction and View Tickets buttons below the Mailing Label input box.

The Submit Button should probably be on the bottom.

These changes should reduce the lines needed by two or three and require less or preferably no scrolling to hit the Submit button.

**Comment by yodigi7** [comment]
Moved the buttons to the side except for submit, can potentially do that but you can also train your crew to just hit enter when they want to submit saving them click. 

If you put the labels in the boxes for the two dates, when they are filled out then the labels will be gone and you won't know which date is which.

If you have add spouse, address, and house member all on one line, they wont be intermingled when adding so it wont be as clear who is spouse, who is house member/address etc., right now the buttons sort of act as dividers and labels in one.

Shrinking the notes/mailing label that you explicitly said you wanted bigger? Again, can just solve all of this by using enter to submit and only scroll if you want and doesn't take that much time.
