### ISSUE TITLE
Ticket Lookup page add checkbox 4 pickups 

### ISSUE THREAD

**Issue by SirGeoffreyB** [yodigi7/credo-database#32]
Add a checkbox on the Ticket Lookup page to document that name tags have been given to the purchaser.

https://credo-jhipster-database.herokuapp.com/person/10001/ticket-view

**Comment by yodigi7** [comment]
This already existed, also added it to the add-ticket just in-case

**Comment by SirGeoffreyB** [comment]
1 Brownie point.
