### ISSUE TITLE
Front End - Phone number validation

### ISSUE THREAD

**Issue by yodigi7** [yodigi7/credo-database#9]

**Comment by yodigi7** [comment]
@SirGeoffreyB Added validation.
Will add a mask later unless you want to require area-code, will be more complex to have optional area code in mask.

**Comment by SirGeoffreyB** [comment]
mandatory area code is fine as long as there is some sort of obvious alert for the data entry person who omits it.

**Comment by yodigi7** [comment]
code pushed to heroku, will take a bit to deploy (wait ~10 min)
